use ecom;

-- BASIC 1-5
-- SELECT CUSTOMERNAME,CITY="HYDERABAD" FROM ORDERS 
-- SELECT CUSTOMERNAME,STATUS FROM ORDERS WHERE STATUS="DELIVERED"
-- SELECT ORDERID,CUSTOMERNAME,AMOUNT FROM ORDERS WHERE AMOUNT>=10000
-- BHAI 4 WALA NAI AYA CHATGPT SE KARA
-- SELECT*FROM ORDERS ORDER BY AMOUNT DESC LIMIT 5;
-- SELECT ORDERID,STATUS FROM ORDERS WHERE STATUS="CANCELLED"