use ecom;

-- BASIC 1-5
SELECT CUSTOMERNAME,CITY="HYDERABAD" FROM ORDERS;
SELECT CUSTOMERNAME,STATUS FROM ORDERS WHERE STATUS="DELIVERED";
SELECT ORDERID,CUSTOMERNAME,AMOUNT FROM ORDERS WHERE AMOUNT>=10000;
-- BHAI 4 WALA NAI AYA CHATGPT SE KARA
SELECT*FROM ORDERS ORDER BY AMOUNT DESC LIMIT 5;
SELECT ORDERID,STATUS FROM ORDERS WHERE STATUS="CANCELLED";
-- INTERMEDIATE 1 TO 5
SELECT SUM(AMOUNT) AS TOTAL_REVENUE FROM ORDERS ;
SELECT AVG(AMOUNT) AS AVG_ORDER_VALUE FROM ORDERS ;
SELECT CITY,SUM(AMOUNT) AS REVENUE_OF_EACH_CITY FROM ORDERS GROUP BY CITY;
SELECT STATUS,COUNT(STATUS) FROM ORDERS
 WHERE STATUS="DELIVERED" OR STATUS="CANCELLED" 
 GROUP BY STATUS 
 